# NumPy 

NumPy (Numerical Python) is a python library used for scientific computing, which provides  multi-dimensional array object. It can also be used as an efficient multi-dimensional container for data.


# installation 

pip3 install numpy

# Importing Numpy:


In [1]:
import numpy
# We directly call the library "numpy" 
numpy.array(['a','b','c'])


array(['a', 'b', 'c'], dtype='<U1')

In [2]:
import numpy as np
# we make reference to the library as “np” instead of “numpy.”
np.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

# Creating NumPy Arrays

In [3]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [4]:
type(my_list)

list

In [5]:
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [6]:
type(my_array)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
ar=np.array(my_matrix)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(ar)

numpy.ndarray

In [10]:
ar+ar

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Numpy Vs Lists
The operations such as data storing, indexing and iterating are similar both in list and numpy. However, Numpy uses less memory, is faster, and more convenient than Lists. We cannot perform calculations (add, subtract, multiply, divide and exponentiation) on Python Lists but we can on Numpy Arrays.


In [11]:
p_list = [4,5,6,7]
print(p_list)
print(p_list*3)

[4, 5, 6, 7]
[4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]


In [12]:
n_array = np.array([4,5,6,7])
print(n_array)
print(n_array*3)

[4 5 6 7]
[12 15 18 21]


In [13]:
print(p_list+p_list)

[4, 5, 6, 7, 4, 5, 6, 7]


In [14]:
print(n_array+n_array)

[ 8 10 12 14]


# Built-in Methods
Lots of build-in functions are available to generate arrays

# arange

Return evenly spaced array within a given interval.

In [15]:
#import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
type(a)

numpy.ndarray

In [17]:
np.append(a,[[7,8,9],[98,87,67]],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 98, 87, 67]])

In [18]:
print(np.append(a, [[17,18,19]],axis =0)) 

[[ 1  2  3]
 [ 4  5  6]
 [17 18 19]]


In [19]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

# zeros and ones
Generate arrays of zeros or ones

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# eye

Creates an identity matrix

In [24]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
print(x.shape)

(3, 3)


# max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [26]:
x= np.arange(1,15,2)
print(x)
x1= np.max(x)
print(x1)

[ 1  3  5  7  9 11 13]
13


In [27]:
x2=np.min(x)
print(x2)

1


In [28]:
a_x1 = np.argmax(x) 
print(a_x1)

6


In [29]:
a_x2 = np.argmin(x)
print(a_x2)

0


# Size 
The size tool returns how many values are in the array

In [30]:
x.size

7

# Shape

Shape is an attribute that arrays have (not a method):

In [31]:
#Vector
arr = np.arange(0,25)
#x=arr.reshape(5,4)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


# Reshape
The reshape tool allows us to change the original dimension of an array.

In [32]:
# Notice the two sets of brackets
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.reshape(5,5).shape

(5, 5)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25,1).shape

(25, 1)

# dtype
You can also grab the data type of the object in the array:

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.dtype

dtype('int64')

In [38]:
#a.dtype

In [39]:
d=np.full((5,5),7)
print (d)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [40]:
x

array([ 1,  3,  5,  7,  9, 11, 13])

In [41]:
arr_sum = np.sum(d)
arr_sum

175

# Doing an operation on a row and column
“ axis = 0 ”  operation is performed on each y-axis within the array.
“ axis = 1 ”  operation is performed on each x-axis within the array. 
“ axis = None” operation on all values in the array, it is default

In [42]:
a = [1,2,3]
b =[5,66,7]
c= [8,5,4]
my_arr1 = np.matrix([a,b,c])
print(my_arr1)

[[ 1  2  3]
 [ 5 66  7]
 [ 8  5  4]]


In [43]:
print(my_arr1.sum(axis =0))

[[14 73 14]]


In [44]:
print(my_arr1.sum(axis =1))

[[ 6]
 [78]
 [17]]


In [45]:
print(my_arr1.sum())

101
