# NumPy Indexing and Selection

#Let's discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
my_arr = np.arange(0,20)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
#The simplest way to pick one or some elements of an array looks very similar to python lists:
#Get a value at an index
my_arr[8]

8

In [5]:
#Get values in a range
my_arr[2:6]

array([2, 3, 4, 5])

# Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
#Setting a value with index range (Broadcasting)
my_arr[3:7]=199

my_arr

array([ 67,  67,  67, 199, 199, 199, 199,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [10]:
my_arr

array([ 67,  67,  67, 199, 199, 199, 199,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [11]:
# array slice
my_arr[4:9]


array([199, 199, 199,   7,   8])

In [12]:
my_arr[:]= 35

In [13]:
my_arr

array([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
       35, 35, 35])

In [14]:
my_arr_copy = my_arr.copy()

my_arr_copy

array([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
       35, 35, 35])

# Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row,col].

In [16]:
a=[1,2,3,4,5]
b=[5,6,7,8,9]
c=[2,45,32,78,65]
d=[3,6,8,9,2]
e=[66,99,88,33,22]
my_matrice = np.matrix([a,b,c,d,e])
my_matrice

matrix([[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [ 2, 45, 32, 78, 65],
        [ 3,  6,  8,  9,  2],
        [66, 99, 88, 33, 22]])

In [38]:
my_matrice[2:4,2:4]

matrix([[32, 78],
        [ 8,  9]])

In [33]:
my_matrice[1:,3:]

matrix([[ 8,  9],
        [78, 65],
        [ 9,  2],
        [33, 22]])

In [34]:
my_matrice[1:3,2:]

matrix([[ 7,  8,  9],
        [32, 78, 65]])

In [41]:
# a tool in Python for creating numeric sequences
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

# NumPy Operations

In [17]:
## Arithmetic

# Let's check some array arithmetic examples:

In [43]:
sam_arr = np.arange(1,9)
sam_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
sam_arr+sam_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [20]:
sam_arr * sam_arr

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [21]:
sam_arr/sam_arr

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
sam_arr - sam_arr

array([0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
1/sam_arr


array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     ])

In [46]:
sam_arr**3

array([  1,   8,  27,  64, 125, 216, 343, 512])

In [47]:
#Taking Square Roots
np.sqrt(sam_arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

In [26]:
#Calcualting exponential (e^)
np.exp(sam_arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03])

In [27]:
np.max(sam_arr) #same as arr.max()

8

In [48]:
my_matrice

matrix([[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [ 2, 45, 32, 78, 65],
        [ 3,  6,  8,  9,  2],
        [66, 99, 88, 33, 22]])

In [28]:
np.diagonal(my_matrice)

array([ 1,  6, 32,  9, 22])

In [29]:
my_matrice

matrix([[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [ 2, 45, 32, 78, 65],
        [ 3,  6,  8,  9,  2],
        [66, 99, 88, 33, 22]])

In [51]:
np.diag(my_matrice, k=3)

array([4, 9])